module.exports = [
  require('./count-certifications'),
  require('./create-project'),
  require('./create-sprint'),
  require('./delete-customer'),
  require('./delete-engineer'),
  require('./find-lazy-employees'),
  require('./get-certifications-count'),
  require('./get-employees-count'),
  require('./get-level-name'),
  require('./get-top-level'),
  require('./most-filled-pod'),
  require('./overused-coworking-spaces'),
  require('./set-user-country'),
  require('./set-user-email'),
  require('./understaffed-projects'),
  require('./unmastered-skills'),
];
